import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TaskProvider from "@/contexts/task/taskProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo | List",
  description: "Generated by Nilesh Gupta For Learning",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TaskProvider>{children}</TaskProvider>
      </body>
    </html>
  );
}
